### ISSUE TITLE
zope.configuration.config.ConfigurationExecutionError: <class 'zope.component.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'cmf.ManagePortal')

### ISSUE THREAD

**Issue by macagua** [IMIO/cpskin.core#25]
When I trying to install the **cpskin.core** package I have a error when started the Zope instance as the following:

```
$ git clone git@github.com:plone-ve/cpskin.core.git 

$ cd cpskin.core

$ virtualenv --python=python2.7 python2.7

$ source ./python2.7/bin/activate

$ pip install -r requirements.txt

$ buildout -vvvvvvvN

$ python --version
Python 2.7.13

$ buildout --version
buildout version 2.13.2

$ buildout -vvvvvvvN

$ ./bin/instance fg
2020-04-24 01:44:31 INFO ZServer HTTP server started at Fri Apr 24 01:44:31 2020
	Hostname: 0.0.0.0
	Port: 8080
2020-04-24 01:44:41 INFO ZODB.blob (17342) Blob directory `/home/macagua/proyectos/plone/plonegov/imio/cpskin.core.ploneve/var/blobstorage` is unused and has no layout marker set. Selected `bushy` layout. 
2020-04-24 01:44:41 INFO ZODB.blob (17342) Blob temporary directory '/home/macagua/proyectos/plone/plonegov/imio/cpskin.core.ploneve/var/blobstorage/tmp' does not exist. Created new directory.
2020-04-24 01:45:44 WARNING plone.behavior Specifying 'for' in behavior 'Related items' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:52 INFO collective.geo.geographer Patching collective.geo.geographer.events's ObjectGeoreferencedEvent to have a 'descriptions' field to handle an issue with p4a.plonevideo.
2020-04-24 01:45:57 WARNING plone.behavior Specifying 'for' in behavior 'Social Media' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Standard Tags' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Hidden Tags' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'I Search Tags' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'I Am Tags' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Related contacts' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Additional searchable text' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Cpskin index view settings' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Cpskin directory view settings' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Images for organizations' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:45:58 WARNING plone.behavior Specifying 'for' in behavior 'Booking fields' if no 'factory' is given has no effect and is superfluous.
/home/macagua/.buildout/eggs/cp27mu/zope.configuration-3.8.1-py2.7.egg/zope/configuration/fields.py:417: UserWarning: You did not specify an i18n translation domain for the 'title' field in /home/macagua/proyectos/plone/plonegov/imio/cpskin.core.ploneve/cpskin/core/menu/configure.zcml
  "'%s' field in %s" % (self.getName(), context.info.file )
2020-04-24 01:46:07 WARNING plone.behavior Specifying 'for' in behavior 'Multilingual Support' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:46:07 WARNING plone.behavior Specifying 'for' in behavior 'Enable Image Cropping' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:46:12 WARNING plone.behavior Specifying 'for' in behavior 'Staging' if no 'factory' is given has no effect and is superfluous.
2020-04-24 01:46:12 INFO Plone OpenID system packages not installed, OpenID support not available
2020-04-24 01:46:14 WARNING fingerpointing common No audit log file specified; audit log view will be disabled
Traceback (most recent call last):
  File "/home/macagua/proyectos/plone/plonegov/imio/cpskin.core.ploneve/parts/instance/bin/interpreter", line 424, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/App/startup.py", line 120, in startup
    load_zcml()
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/macagua/.buildout/eggs/cp27mu/Zope2-2.13.28-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/macagua/.buildout/eggs/cp27mu/zope.configuration-3.8.1-py2.7.egg/zope/configuration/xmlconfig.py", line 648, in file
    context.execute_actions()
  File "/home/macagua/.buildout/eggs/cp27mu/zope.configuration-3.8.1-py2.7.egg/zope/configuration/config.py", line 691, in execute_actions
    callable(*args, **kw)
  File "/home/macagua/.buildout/eggs/cp27mu/AccessControl-3.0.11-py2.7-linux-x86_64.egg/AccessControl/security.py", line 165, in protectClass
    permission = getUtility(IPermission, name=permission_id)
  File "/home/macagua/.buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 169, in getUtility
    raise ComponentLookupError(interface, name)
zope.configuration.config.ConfigurationExecutionError: <class 'zope.component.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'cmf.ManagePortal')
  in:
  File "/home/macagua/.buildout/eggs/cp27mu/collective.lesscss-2.0.3-py2.7.egg/collective/lesscss/browser/configure.zcml", line 27.4-32.8
      <browser:page
        name="lesscss-controlpanel"
        for="Products.CMFPlone.interfaces.IPloneSiteRoot"
        class=".controlpanel.LESSCSSControlPanel"
        permission="cmf.ManagePortal"
        />
```

Possible solution:

- https://docs.plone.org/manage/troubleshooting/exceptions.html#componentlookuperror-cmf-manageportal

**Comment by bsuttor** [comment]
Fixed by https://github.com/IMIO/cpskin.core/pull/26

**Comment by macagua** [comment]
@bsuttor Thanks :-)
